title: Template Repository SE Lab
description: A starter template project website
theme: just-the-docs

# url: https://just-the-docs.github.io

# aux_links:
#   Project GitHub Repository: https://github.com/RUB-SE-LAB/xxxx
